version: '3.4'

services:
  customer-service.api:
    image: ${DOCKER_REGISTRY-}customerserviceapi
    build:
      context: .
      dockerfile: Customer-Service.API/Dockerfile
    ports:
      - "5000:80"  # Adjust if necessary
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - rabbitmq

  postgres:
    image: postgres:15  # Use the version that suits your needs
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.3  # Use the version that suits your needs
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # Management UI port

volumes:
  postgres-data:
